apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: k8s-demo
        image: uzair158/k8s-python-sample
        ports:
        - name: python-port
          containerPort: 5001
